window.__QUIZ_EXAM_40__ = {
  title: "Đề mô phỏng Anh văn 3 - 40 câu",
  count: 40,
  fixedExam: true,
  sourceCounts: {
    vocab: 8,
    grammar: 14,
    cloze: 8,
    reading: 10,
  },
  questions: [
    {
      chapter: "7",
      question: "[Vocab - Unit 7] This is a person who has applied for a job.",
      options: { A: "application", B: "manager", C: "applicant", D: "officer" },
      answer: "C",
    },
    {
      chapter: "7",
      question: "[Vocab - Unit 7] This is a letter that says positive things about you and the way you work.",
      options: { A: "reference", B: "salary", C: "promotion", D: "branch" },
      answer: "A",
    },
    {
      chapter: "8",
      question: "[Vocab - Unit 8] If you use this to find your way, you will not get lost.",
      options: { A: "battery", B: "GPS", C: "torch", D: "towel" },
      answer: "B",
    },
    {
      chapter: "8",
      question: "[Vocab - Unit 8] This cooks food very quickly.",
      options: { A: "microwave oven", B: "hair dryer", C: "camera", D: "laptop" },
      answer: "A",
    },
    {
      chapter: "9",
      question: "[Vocab - Unit 9] A cheap holiday where travel, hotel and meals are arranged for you is a:",
      options: { A: "backpacking trip", B: "package tour", C: "city break", D: "field trip" },
      answer: "B",
    },
    {
      chapter: "10",
      question: "[Vocab - Unit 10] A famous picture or symbol used by a company is called a:",
      options: { A: "logo", B: "label", C: "pattern", D: "button" },
      answer: "A",
    },
    {
      chapter: "11",
      question: "[Vocab - Unit 11] A person who studies the past is a:",
      options: { A: "collector", B: "historian", C: "designer", D: "engineer" },
      answer: "B",
    },
    {
      chapter: "12",
      question: "[Vocab - Unit 12] An animal that can live both in water and on land is an:",
      options: { A: "insect", B: "amphibian", C: "mammal", D: "reptile" },
      answer: "B",
    },
    {
      chapter: "7",
      question: "[Grammar - Unit 7] I ______ my mobile phone. Do you know where it is?",
      options: { A: "lost", B: "have lost", C: "has lost", D: "was losing" },
      answer: "B",
    },
    {
      chapter: "7",
      question: "[Grammar - Unit 7] How long ______ your car? - Since Christmas.",
      options: { A: "did you have", B: "have you had", C: "you had", D: "do you have" },
      answer: "B",
    },
    {
      chapter: "7",
      question: "[Grammar - Unit 7] My flat is ______ the tenth floor.",
      options: { A: "on", B: "at", C: "in", D: "to" },
      answer: "A",
    },
    {
      chapter: "8",
      question: "[Grammar - Unit 8] If you heat water to 100°C, it ______.",
      options: { A: "boiled", B: "will boil", C: "boils", D: "is boiling" },
      answer: "C",
    },
    {
      chapter: "8",
      question: "[Grammar - Unit 8] The computer will not work again if you ______ it in.",
      options: { A: "won't plug", B: "don't plug", C: "didn't plug", D: "aren't plugging" },
      answer: "B",
    },
    {
      chapter: "8",
      question: "[Grammar - Unit 8] He’s the man ______ invented a new kind of bicycle.",
      options: { A: "who", B: "whom", C: "whose", D: "where" },
      answer: "A",
    },
    {
      chapter: "9",
      question: "[Grammar - Unit 9] By the time we got to the airport, the plane ______.",
      options: { A: "left", B: "has left", C: "had left", D: "was leaving" },
      answer: "C",
    },
    {
      chapter: "9",
      question: "[Grammar - Unit 9] Who ______ to the museum with you last weekend?",
      options: { A: "did go", B: "went", C: "was go", D: "going" },
      answer: "B",
    },
    {
      chapter: "10",
      question: "[Grammar - Unit 10] Wind turbines ______ in many countries today.",
      options: { A: "use", B: "used", C: "are used", D: "were using" },
      answer: "C",
    },
    {
      chapter: "10",
      question: "[Grammar - Unit 10] My grandfather ______ live in the countryside, but now he lives in the city.",
      options: { A: "used to", B: "use to", C: "is used to", D: "was used to" },
      answer: "A",
    },
    {
      chapter: "11",
      question: "[Grammar - Unit 11] Mum ______ us she would be late home.",
      options: { A: "said", B: "told", C: "spoke", D: "talked" },
      answer: "B",
    },
    {
      chapter: "11",
      question: "[Grammar - Unit 11] 'I’ll see you on Monday.' Jane told me that she ______ me on Monday.",
      options: { A: "will see", B: "would see", C: "saw", D: "had seen" },
      answer: "B",
    },
    {
      chapter: "12",
      question: "[Grammar - Unit 12] If Paul ______ television so often, he would have more time for homework.",
      options: { A: "doesn't watch", B: "won't watch", C: "didn't watch", D: "hasn't watched" },
      answer: "C",
    },
    {
      chapter: "12",
      question: "[Grammar - Unit 12] Has ______ seen my keys?",
      options: { A: "anyone", B: "anywhere", C: "nothing", D: "somewhere" },
      answer: "A",
    },
    {
      chapter: "7",
      question: "[Cloze 1 - Unit 7] Read the mini passage and choose the best answer for blank (1).\nLan has worked for the same company ______ 2022, and she has already applied for a better position.\nBlank (1):",
      options: { A: "for", B: "since", C: "from", D: "during" },
      answer: "B",
    },
    {
      chapter: "7",
      question: "[Cloze 1 - Unit 7] Read the mini passage and choose the best answer for blank (2).\nLan has worked for the same company since 2022, and she has already ______ for a better position.\nBlank (2):",
      options: { A: "applied", B: "applying", C: "apply", D: "application" },
      answer: "A",
    },
    {
      chapter: "7",
      question: "[Cloze 1 - Unit 7] Read the mini passage and choose the best answer for blank (3).\nHer manager says she is hardworking and gives a very positive ______.\nBlank (3):",
      options: { A: "salary", B: "reference", C: "commute", D: "branch" },
      answer: "B",
    },
    {
      chapter: "7",
      question: "[Cloze 1 - Unit 7] Read the mini passage and choose the best answer for blank (4).\nIf she gets the new job, she will probably earn more money and get a ______.\nBlank (4):",
      options: { A: "promotion", B: "basement", C: "traffic", D: "tunnel" },
      answer: "A",
    },
    {
      chapter: "10",
      question: "[Cloze 2 - Unit 10] Read the mini passage and choose the best answer for blank (1).\nThis water bottle is made ______ recycled plastic.\nBlank (1):",
      options: { A: "by", B: "of", C: "from", D: "with" },
      answer: "C",
    },
    {
      chapter: "10",
      question: "[Cloze 2 - Unit 10] Read the mini passage and choose the best answer for blank (2).\nIt ______ in a small factory near the city.\nBlank (2):",
      options: { A: "produced", B: "is produced", C: "produces", D: "was producing" },
      answer: "B",
    },
    {
      chapter: "10",
      question: "[Cloze 2 - Unit 10] Read the mini passage and choose the best answer for blank (3).\nIn the past, people ______ use glass bottles much more often.\nBlank (3):",
      options: { A: "used to", B: "use to", C: "were used to", D: "using to" },
      answer: "A",
    },
    {
      chapter: "10",
      question: "[Cloze 2 - Unit 10] Read the mini passage and choose the best answer for blank (4).\nNow many companies want to design products that are cheaper, greener and more ______.\nBlank (4):",
      options: { A: "effectively", B: "effective", C: "effect", D: "effected" },
      answer: "B",
    },
    {
      chapter: "11",
      question: "[Reading 1 - Unit 11] Read the passage and answer the question.\nTom visited an old polar research hut in Antarctica. Inside, he saw food, tools and notebooks that had stayed there for many years because the freezing weather preserved them. He said it felt as if the explorer had only just left.\nWhy were the objects inside the hut still there after so many years?",
      options: { A: "Because tourists cleaned the hut every week", B: "Because the freezing temperature preserved them", C: "Because the hut was under the sea", D: "Because the objects were made of plastic" },
      answer: "B",
    },
    {
      chapter: "11",
      question: "[Reading 1 - Unit 11] Read the passage and answer the question.\nTom visited an old polar research hut in Antarctica. Inside, he saw food, tools and notebooks that had stayed there for many years because the freezing weather preserved them. He said it felt as if the explorer had only just left.\nWhat did Tom see inside the hut?",
      options: { A: "Only modern machines", B: "Food, tools and notebooks", C: "Wild animals", D: "Maps of the moon" },
      answer: "B",
    },
    {
      chapter: "11",
      question: "[Reading 1 - Unit 11] Read the passage and answer the question.\nTom visited an old polar research hut in Antarctica. Inside, he saw food, tools and notebooks that had stayed there for many years because the freezing weather preserved them. He said it felt as if the explorer had only just left.\nWhere was the hut located?",
      options: { A: "In Antarctica", B: "In the Sahara", C: "In Tokyo", D: "In Venice" },
      answer: "A",
    },
    {
      chapter: "11",
      question: "[Reading 1 - Unit 11] Read the passage and answer the question.\nTom visited an old polar research hut in Antarctica. Inside, he saw food, tools and notebooks that had stayed there for many years because the freezing weather preserved them. He said it felt as if the explorer had only just left.\nHow did Tom say the hut felt?",
      options: { A: "As if the explorer had only just left", B: "As if it had been built yesterday", C: "As if nobody had ever used it", D: "As if it belonged to a museum guide" },
      answer: "A",
    },
    {
      chapter: "11",
      question: "[Reading 1 - Unit 11] Read the passage and answer the question.\nTom visited an old polar research hut in Antarctica. Inside, he saw food, tools and notebooks that had stayed there for many years because the freezing weather preserved them. He said it felt as if the explorer had only just left.\nWhat is the main idea of the passage?",
      options: { A: "A hut in freezing conditions can preserve history", B: "Antarctica is the best place for holidays", C: "Modern explorers prefer hotels", D: "Tom lost his notebook in the snow" },
      answer: "A",
    },
    {
      chapter: "8",
      question: "[Reading 2 - Unit 8] Read the passage and answer the question.\nA group of students built a smart plant pot. If the soil becomes dry, the pot sends a message to the owner's phone. The students say the device helps busy people take care of their plants and may save water because it gives information at the right time.\nWhat happens if the soil becomes dry?",
      options: { A: "The pot breaks", B: "The phone switches off", C: "The pot sends a message", D: "The plant moves outside" },
      answer: "C",
    },
    {
      chapter: "8",
      question: "[Reading 2 - Unit 8] Read the passage and answer the question.\nA group of students built a smart plant pot. If the soil becomes dry, the pot sends a message to the owner's phone. The students say the device helps busy people take care of their plants and may save water because it gives information at the right time.\nWho built the smart plant pot?",
      options: { A: "A famous company", B: "A group of students", C: "A travel guide", D: "A historian" },
      answer: "B",
    },
    {
      chapter: "8",
      question: "[Reading 2 - Unit 8] Read the passage and answer the question.\nA group of students built a smart plant pot. If the soil becomes dry, the pot sends a message to the owner's phone. The students say the device helps busy people take care of their plants and may save water because it gives information at the right time.\nWhy may the device save water?",
      options: { A: "Because it waters the plant all day", B: "Because it tells people exactly when the plant needs water", C: "Because it uses no electricity", D: "Because it changes the weather" },
      answer: "B",
    },
    {
      chapter: "8",
      question: "[Reading 2 - Unit 8] Read the passage and answer the question.\nA group of students built a smart plant pot. If the soil becomes dry, the pot sends a message to the owner's phone. The students say the device helps busy people take care of their plants and may save water because it gives information at the right time.\nWhich group of people would find the pot especially useful?",
      options: { A: "People who are too busy to check plants often", B: "People who hate technology", C: "People who never use phones", D: "People who only grow trees in forests" },
      answer: "A",
    },
    {
      chapter: "8",
      question: "[Reading 2 - Unit 8] Read the passage and answer the question.\nA group of students built a smart plant pot. If the soil becomes dry, the pot sends a message to the owner's phone. The students say the device helps busy people take care of their plants and may save water because it gives information at the right time.\nWhat is the main purpose of the passage?",
      options: { A: "To advertise a holiday", B: "To describe a useful invention", C: "To teach reported speech", D: "To explain ancient history" },
      answer: "B",
    },
  ],
};
