window.__QUIZ_EXAM_40__ = {
  title: "Đề CLO Anh văn 3 - 40 câu",
  count: 40,
  fixedExam: true,
  sourceCounts: {
    vocab: 8,
    grammar: 16,
    cloze: 8,
    reading: 8,
  },
  questions: [
    {
      chapter: "7",
      question: "[Vocab - Unit 7] A person who has applied for a job is called an ______.",
      options: { A: "applicant", B: "assistant", C: "audience", D: "architect" },
      answer: "A",
    },
    {
      chapter: "7",
      question: "[Vocab - Unit 7] A letter that says positive things about your work is a ______.",
      options: { A: "promotion", B: "reference", C: "salary", D: "schedule" },
      answer: "B",
    },
    {
      chapter: "8",
      question: "[Vocab - Unit 8] A device that helps you find your way when you travel is a ______.",
      options: { A: "microwave", B: "keyboard", C: "GPS", D: "plug" },
      answer: "C",
    },
    {
      chapter: "8",
      question: "[Vocab - Unit 8] A small useful piece of technology, such as a smartwatch, is a ______.",
      options: { A: "gadget", B: "branch", C: "reference", D: "journey" },
      answer: "A",
    },
    {
      chapter: "9",
      question: "[Vocab - Unit 9] When you join a class or course, you ______ on it.",
      options: { A: "apply", B: "enrol", C: "argue", D: "invent" },
      answer: "B",
    },
    {
      chapter: "10",
      question: "[Vocab - Unit 10] A holiday with exciting outdoor activities is an ______ holiday.",
      options: { A: "ancient", B: "electrical", C: "adventure", D: "formal" },
      answer: "C",
    },
    {
      chapter: "11",
      question: "[Vocab - Unit 11] A person who studies and writes about past events is a ______.",
      options: { A: "historian", B: "journalist", C: "tourist", D: "photographer" },
      answer: "A",
    },
    {
      chapter: "12",
      question: "[Vocab - Unit 12] The natural home of an animal or plant is its ______.",
      options: { A: "habit", B: "habitat", C: "harvest", D: "highland" },
      answer: "B",
    },
    {
      chapter: "7",
      question: "[Grammar - Unit 7] I ______ my keys. Have you seen them anywhere?",
      options: { A: "lost", B: "have lost", C: "am losing", D: "had lost" },
      answer: "B",
    },
    {
      chapter: "7",
      question: "[Grammar - Unit 7] How long ______ in this company?",
      options: { A: "do you work", B: "did you work", C: "have you worked", D: "are you working" },
      answer: "C",
    },
    {
      chapter: "7",
      question: "[Grammar - Unit 7] My office is ______ the third floor, next to the meeting room.",
      options: { A: "on", B: "at", C: "for", D: "between" },
      answer: "A",
    },
    {
      chapter: "8",
      question: "[Grammar - Unit 8] If you heat ice, it ______.",
      options: { A: "melt", B: "melts", C: "will melt", D: "melted" },
      answer: "B",
    },
    {
      chapter: "8",
      question: "[Grammar - Unit 8] If I see Maria tomorrow, I ______ her the message.",
      options: { A: "tell", B: "told", C: "will tell", D: "am telling" },
      answer: "C",
    },
    {
      chapter: "8",
      question: "[Grammar - Unit 8] The woman ______ works in that lab invented a useful device.",
      options: { A: "who", B: "which", C: "where", D: "whose" },
      answer: "A",
    },
    {
      chapter: "9",
      question: "[Grammar - Unit 9] By the time I arrived, the lesson ______.",
      options: { A: "started", B: "has started", C: "had started", D: "was starting" },
      answer: "C",
    },
    {
      chapter: "9",
      question: "[Grammar - Unit 9] Who ______ you about the new language course?",
      options: { A: "did tell", B: "told", C: "was tell", D: "telling" },
      answer: "B",
    },
    {
      chapter: "9",
      question: "[Grammar - Unit 9] After he ______ the email, he enrolled on the course.",
      options: { A: "read", B: "reads", C: "had read", D: "was reading" },
      answer: "C",
    },
    {
      chapter: "10",
      question: "[Grammar - Unit 10] These bags ______ from recycled plastic.",
      options: { A: "make", B: "made", C: "are made", D: "are making" },
      answer: "C",
    },
    {
      chapter: "10",
      question: "[Grammar - Unit 10] We ______ go to Da Lat every summer when I was a child.",
      options: { A: "use to", B: "used to", C: "are used to", D: "were used to" },
      answer: "B",
    },
    {
      chapter: "10",
      question: "[Grammar - Unit 10] Tourist information ______ near the station.",
      options: { A: "can find", B: "can be found", C: "can found", D: "can be finding" },
      answer: "B",
    },
    {
      chapter: "11",
      question: "[Grammar - Unit 11] Nam said he ______ tired after the long journey.",
      options: { A: "is", B: "was", C: "has been", D: "will be" },
      answer: "B",
    },
    {
      chapter: "11",
      question: "[Grammar - Unit 11] The guide ______ us that the museum closed at 5 p.m.",
      options: { A: "said", B: "told", C: "spoke", D: "talked" },
      answer: "B",
    },
    {
      chapter: "12",
      question: "[Grammar - Unit 12] If I ______ more free time, I would join the nature club.",
      options: { A: "have", B: "had", C: "will have", D: "am having" },
      answer: "B",
    },
    {
      chapter: "12",
      question: "[Grammar - Unit 12] There isn't ______ in the room. Everyone has gone home.",
      options: { A: "someone", B: "anyone", C: "everyone", D: "no one" },
      answer: "B",
    },
    {
      chapter: "7",
      question: "[Cloze - Work] Choose the best answer for blank (1).\nMinh has worked for the same company ______ three years. He likes his job, but now he wants a better position.",
      options: { A: "since", B: "for", C: "from", D: "already" },
      answer: "B",
    },
    {
      chapter: "7",
      question: "[Cloze - Work] Choose the best answer for blank (2).\nHe has just sent his CV and a ______ from his manager to another company.",
      options: { A: "reference", B: "gadget", C: "habitat", D: "holiday" },
      answer: "A",
    },
    {
      chapter: "10",
      question: "[Cloze - Travel] Choose the best answer for blank (1).\nLast summer, we went on an adventure holiday. The hotel room ______ every day, and breakfast was served at 7 a.m.",
      options: { A: "cleaned", B: "was cleaned", C: "is cleaning", D: "has cleaned" },
      answer: "B",
    },
    {
      chapter: "10",
      question: "[Cloze - Travel] Choose the best answer for blank (2).\nWhen I was younger, I ______ spend all day on the beach, but now I prefer walking tours.",
      options: { A: "used to", B: "use to", C: "am used to", D: "using to" },
      answer: "A",
    },
    {
      chapter: "12",
      question: "[Cloze - Nature] Choose the best answer for blank (1).\nIf people ______ less plastic, the environment would be cleaner.",
      options: { A: "use", B: "used", C: "will use", D: "have used" },
      answer: "B",
    },
    {
      chapter: "12",
      question: "[Cloze - Nature] Choose the best answer for blank (2).\nMany animals lose their natural ______ because forests are being cut down.",
      options: { A: "habitat", B: "history", C: "gadget", D: "reference" },
      answer: "A",
    },
    {
      chapter: "8",
      question: "[Cloze - Technology] Choose the best answer for blank (1).\nMy brother bought a new GPS, ______ helps him find places quickly when he travels.",
      options: { A: "who", B: "which", C: "where", D: "when" },
      answer: "B",
    },
    {
      chapter: "8",
      question: "[Cloze - Technology] Choose the best answer for blank (2).\nIf the battery is low, the device ______ stop working.",
      options: { A: "will", B: "would", C: "did", D: "has" },
      answer: "A",
    },
    {
      chapter: "11",
      question: "[Reading 1] Read the passage and choose the best answer.\nLast weekend, Linh visited a history museum with her classmates. First, they listened to a guide talking about an ancient city. Then they looked at old tools, clothes and maps. Linh liked the trip because she could understand the lesson better after seeing real objects.\nWhy did Linh like the trip?",
      options: { A: "Because she bought many old maps", B: "Because she understood the lesson better", C: "Because the museum was near her home", D: "Because she met a famous writer there" },
      answer: "B",
    },
    {
      chapter: "11",
      question: "[Reading 1] Read the passage and choose the best answer.\nLast weekend, Linh visited a history museum with her classmates. First, they listened to a guide talking about an ancient city. Then they looked at old tools, clothes and maps. Linh liked the trip because she could understand the lesson better after seeing real objects.\nWhat did the students do first?",
      options: { A: "They bought tickets for the cinema", B: "They looked at old clothes", C: "They listened to a guide", D: "They drew a city map" },
      answer: "C",
    },
    {
      chapter: "11",
      question: "[Reading 1] Read the passage and choose the best answer.\nLast weekend, Linh visited a history museum with her classmates. First, they listened to a guide talking about an ancient city. Then they looked at old tools, clothes and maps. Linh liked the trip because she could understand the lesson better after seeing real objects.\nWhat could they see in the museum?",
      options: { A: "Old tools, clothes and maps", B: "Modern computers and cameras", C: "Only photographs", D: "Wild animals" },
      answer: "A",
    },
    {
      chapter: "11",
      question: "[Reading 1] Read the passage and choose the best answer.\nLast weekend, Linh visited a history museum with her classmates. First, they listened to a guide talking about an ancient city. Then they looked at old tools, clothes and maps. Linh liked the trip because she could understand the lesson better after seeing real objects.\nWhat is the main idea of the passage?",
      options: { A: "A school trip helped students learn history better", B: "History is more difficult than science", C: "Museums are only for tourists", D: "Ancient cities are dangerous places" },
      answer: "A",
    },
    {
      chapter: "12",
      question: "[Reading 2] Read the passage and choose the best answer.\nA small group of students joined a clean-up day at a local river. They collected plastic bottles, cans and bags from the water and the riverbank. At the end of the day, the area looked much cleaner, and the students agreed that simple actions can help protect nature.\nWhat did the students collect?",
      options: { A: "Books and notebooks", B: "Plastic bottles, cans and bags", C: "Only pieces of wood", D: "Fish and plants" },
      answer: "B",
    },
    {
      chapter: "12",
      question: "[Reading 2] Read the passage and choose the best answer.\nA small group of students joined a clean-up day at a local river. They collected plastic bottles, cans and bags from the water and the riverbank. At the end of the day, the area looked much cleaner, and the students agreed that simple actions can help protect nature.\nWhere did the activity happen?",
      options: { A: "At a local river", B: "In a shopping centre", C: "At a history museum", D: "In a classroom" },
      answer: "A",
    },
    {
      chapter: "12",
      question: "[Reading 2] Read the passage and choose the best answer.\nA small group of students joined a clean-up day at a local river. They collected plastic bottles, cans and bags from the water and the riverbank. At the end of the day, the area looked much cleaner, and the students agreed that simple actions can help protect nature.\nHow did the area look after the activity?",
      options: { A: "More crowded", B: "Much cleaner", C: "More dangerous", D: "Exactly the same" },
      answer: "B",
    },
    {
      chapter: "12",
      question: "[Reading 2] Read the passage and choose the best answer.\nA small group of students joined a clean-up day at a local river. They collected plastic bottles, cans and bags from the water and the riverbank. At the end of the day, the area looked much cleaner, and the students agreed that simple actions can help protect nature.\nWhat lesson did the students learn?",
      options: { A: "Only governments can protect nature", B: "Cleaning rivers is impossible", C: "Simple actions can help protect nature", D: "Students should avoid outdoor activities" },
      answer: "C",
    },
  ],
};
